name: BoYouQuan UI CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: actions/setup-node@v2
        uses: actions/setup-node@v2   
        with:
          node: 20.17.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: actions/setup-node@v2
        uses: actions/setup-node@v2   
        with:
          node: 20.17.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip
        run: zip -r build.zip ./build
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: './build.zip'
          target: '/usr/share/nginx/html/boyouquan-ui'
      - name: Start Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            unzip /usr/share/nginx/html/boyouquan-ui/build.zip -d /usr/share/nginx/html/boyouquan-ui/
            rm -rf /usr/share/nginx/html/boyouquan-ui/monthly-selected/
            mv /usr/share/nginx/html/boyouquan-ui/build/ /usr/share/nginx/html/boyouquan-ui/monthly-selected/
            service nginx reload
            echo "Server started!"